# Generated by Django 4.2.6 on 2023-10-16 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0002_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedsessionPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.TextField()),
                ('confidence', models.FloatField()),
                ('image_path', models.TextField()),
                ('resnet50_label', models.CharField(max_length=200)),
                ('resnet50_confidence', models.FloatField()),
                ('senet50_label', models.CharField(max_length=200)),
                ('senet50_confidence', models.FloatField()),
                ('vgg16_label', models.CharField(max_length=200)),
                ('vgg16_confidence', models.FloatField()),
                ('elected_label', models.CharField(max_length=200)),
                ('medsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medapp.medsession')),
            ],
        ),
    ]
