# Generated by Django 4.2.6 on 2023-10-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0003_medsessionperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='medsessionperson',
            name='image_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
