# Generated by Django 4.2.6 on 2023-10-18 05:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0004_medsessionperson_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='medsessionperson',
            name='corrected_label',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='medsession',
            name='course',
            field=models.CharField(default='n/a', max_length=400),
        ),
        migrations.AlterField(
            model_name='medsession',
            name='day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='medsession',
            name='lecturer',
            field=models.CharField(default='n/a', max_length=400),
        ),
        migrations.AlterField(
            model_name='medsession',
            name='room',
            field=models.CharField(max_length=50),
        ),
    ]
