# Generated by Django 4.2.6 on 2023-10-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0005_medsessionperson_corrected_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='group',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], default='', max_length=2),
            preserve_default=False,
        ),
    ]
