# Generated by Django 4.2.6 on 2023-10-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0006_person_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='label',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='year_b',
            field=models.CharField(default='22-26', max_length=20),
        ),
    ]
