# Generated by Django 4.2.6 on 2023-10-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0007_person_label_person_year_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='arname',
            field=models.CharField(default='', max_length=450),
        ),
        migrations.AlterField(
            model_name='person',
            name='year',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='3', max_length=1),
        ),
    ]
