# Generated by Django 4.2.6 on 2023-10-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0008_person_arname_alter_person_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='medsessionperson',
            name='added_by',
            field=models.CharField(choices=[('0', '0')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='medsessionperson',
            name='box',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='medsessionperson',
            name='confidence',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='medsessionperson',
            name='corrected_label',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medsessionperson',
            name='elected_label',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medsessionperson',
            name='image_path',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='medsessionperson',
            name='image_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medsessionperson',
            name='resnet50_confidence',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='medsessionperson',
            name='resnet50_label',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medsessionperson',
            name='senet50_confidence',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='medsessionperson',
            name='senet50_label',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medsessionperson',
            name='vgg16_confidence',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='medsessionperson',
            name='vgg16_label',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
