# Generated by Django 4.2.6 on 2023-10-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0009_medsessionperson_added_by_alter_medsessionperson_box_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medsessionperson',
            name='elected_label',
            field=models.CharField(max_length=200),
        ),
    ]
