# Generated by Django 4.2.6 on 2023-11-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0011_taskstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='TimeTaken',
            field=models.IntegerField(default=0),
        ),
    ]
