# Generated by Django 4.2.6 on 2023-11-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0012_taskstatus_timetaken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hall_code', models.CharField(max_length=15)),
                ('hall_section', models.CharField(choices=[('PBL', 'PBL'), ('Clinical', 'Clinical'), ('Bedside Teaching', 'Bedside Teaching')], default='', max_length=50)),
                ('notes', models.CharField(default='', max_length=250)),
                ('type', models.CharField(choices=[('Lecture Room', 'Lecture Room'), ('Skill Lab', 'Skill Lab'), ('Think Tank', 'Think Tank'), ('Virtual Hospital', 'Virtual Hospital'), ('X-Reality', 'X-Reality'), ('Amphitheatre', 'Amphitheatre'), ('Operating Theatre', 'Operating Theatre')], default='Lecture Room', max_length=50)),
                ('floor', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], default='', max_length=50)),
                ('building', models.CharField(choices=[('B2', 'B2'), ('B3', 'B3'), ('B4', 'B4'), ('B5', 'B5'), ('B6', 'B6'), ('Hospital', 'Hospital'), ('Other', 'Other')], default='B2', max_length=50)),
                ('modifytime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
